## Database and redis RUN MY-LEARNING NOT FROM USER
services:
  postgres:
    image: postgres:15
    container_name: daily-script-cont
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5555:5432"
    volumes:
      - daily_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ems-user -d ems_database"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  daily_data:
